### ISSUE TITLE
Setup travis to get daily data in automated way

### ISSUE THREAD

**Issue by zelima** [otruja/bitcoin-prices#4]
As a data user, I want the data to be updated continuously so that I have up to date data.

## Acceptance Criteria

*  [x] data is up-to-date anytime I come here

## Tasks

* [x] read about travis https://travis-ci.org/
* [x] take a look at the example: https://github.com/datapackage-examples/sample-csv/blob/master/.travis.yml
  * [x] Note: This one pushed data to datahub.io - we need it to be pushed here, back to github for now. 
* [x] implement

## Analysis

TODO

**Comment by otruja** [comment]
```
$ python scripts/process.py
Traceback (most recent call last):
  File "scripts/process.py", line 9, in <module>
    ur.urlretrieve(url, filename = raw_data_file)[1]
  File "/opt/python/3.6.3/lib/python3.6/urllib/request.py", line 258, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '../archive/bitcoin-prices.csv'
```

**Comment by zelima** [comment]
@otruja could you please be more descriptive for future when describing issues. Is this coming from Travis only, or is this a general issue? 

From your standup:
> this error on Travis console; @zelima please take a look when you have a free minute, I believe that's infamous / vs \ in path problem;

I doubt this is related to that problem as error clearly says `No such file or directory` - I guess you should first create a directory, that you want to place the file in, and then place the downloaded file there. 

BTW I've just cloned and got the same error.

**Comment by otruja** [comment]
@zelima I think that `more descriptive` is very subjective term. I can't measure or compare my previous issues with this last one, even though I believe they differ much. As a result I can't improve on writing them issues, since there's no rules or checklist to rely on. 
I've just googled `The 5 'W's - Who, What, Where, When and Why` scheme.  I assume, that will be the good start.

And yes, figured out with morning coffee (had aha! moment, lol) that Travis creates sorta empty environment to run the script. I assume Travis downloads the repo, but not places it in the environment itself or something, so that directories are missing and throw an error. 
Anyways, going to find out how to create directories via *nix console, and then will report with what happened.

**Comment by otruja** [comment]
And that's not a missing directory issue :)

Apparently if the directories are in place, and the script can't find them - something is wrong with the description of the path (i.e. `'../archive/bitcoin-prices.csv'`) in the script itself. I assume since I call the script by command `python scripts/process.py` that the cursor (or how you call that?) stays in the main directory, so it can't go up the tree by followin the `..` command.

```
$ mkdir archive
mkdir: cannot create directory ‘archive’: File exists

0.01s$ mkdir data
mkdir: cannot create directory ‘data’: File exists

0.68s$ python scripts/process.py
Traceback (most recent call last):
  File "scripts/process.py", line 9, in <module>
    ur.urlretrieve(url, filename = raw_data_file)
  File "/opt/python/3.6.3/lib/python3.6/urllib/request.py", line 258, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '../archive/bitcoin-prices.csv'
```

**Comment by zelima** [comment]
@otruja I defined 'descriptive" in the very next sentence:
>Is this coming from Travis only, or is this a general issue

I understand that It's hard to come up with the perfect description and I do not require that :). but pasting only the traceback is usually not very helpful without context. 

Eg: your comment, that I quoted above, is more than enough to complete the issue description. without it, for somebody who's not familiar with the context (or even for you in a future), would be hard to help you with debug.

As for your problem, I strongly believe it will be solved if you remove `../` from your paths (as you are running it from the root directory, not from `scripts/`) 
```
raw_data_file = 'archive/bitcoin-prices.csv'
final_data_file = 'data/bitcoin-prices.csv'

# Instead of
raw_data_file = '../archive/bitcoin-prices.csv'
final_data_file = '../data/bitcoin-prices.csv'
```

As I said above, it is **not** related to Travis, I have the same problem if I run the script from the root directory (you should have the same problem)

**Comment by otruja** [comment]
@zelima Oh hi :smile:

**Comment by zelima** [comment]
@otruja problem is that you are running the script from the **root** directory, not in the fact that the directories do not exist

**Comment by otruja** [comment]
@zelima I've fixed the script and `.travis.yml`, and it finally works :smile_cat: 

But now I can't figure out how to upload the data to the GitHub.
What I did:

- following [this manual](https://docs.travis-ci.com/user/deployment/releases), I've added lines to the `.travis.yml`:
```
before_deploy:
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "/data/bitcoin-prices.csv"
  skip_cleanup: true
```
- I've created github token and set it up as Travis's Environment Variable GITHUB_TOKEN for the bitcoin project

The result is:

```
$ python scripts/process.py
The command "python scripts/process.py" exited with 0.
before_deploy
0.01s$ git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
dpl_0
1.65s$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Successfully installed dpl-1.9.6
1 gem installed
dpl.1
Installing deploy dependencies
Successfully installed multipart-post-2.0.0
Successfully installed faraday-0.15.0
Successfully installed public_suffix-3.0.2
Successfully installed addressable-2.5.2
Successfully installed sawyer-0.8.1
Successfully installed octokit-4.6.2
Successfully installed mime-types-2.99.3
Successfully installed dpl-releases-1.9.6
8 gems installed
/home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.0/lib/faraday/response.rb:9:in `block in call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.0/lib/faraday/response.rb:61:in `on_complete'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.0/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.0/lib/faraday/rack_builder.rb:143:in `build_response'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.0/lib/faraday/connection.rb:387:in `run_request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.0/lib/faraday/connection.rb:138:in `get'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/connection.rb:19:in `get'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/users.rb:34:in `user'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.6/lib/dpl/provider/releases.rb:48:in `user'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.6/lib/dpl/provider/releases.rb:73:in `setup_auth'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.6/lib/dpl/provider/releases.rb:77:in `check_auth'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/provider.rb:182:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/provider.rb:181:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
dpl.2
Preparing deploy
failed to deploy
```

**Comment by zelima** [comment]
@otruja you are tagging and doing the new release - That's not what you need. You need to commit and push back to GitHub

**Comment by zelima** [comment]
@otruja Have you tried to google it? Eg this is the First from google search result https://gist.github.com/willprice/e07efd73fb7f13f917ea

**Comment by otruja** [comment]
Figured some git commands, now the `.travis.yml` looks like that:

```
language: python
python:
- "3.6"
script:
- python scripts/process.py
after_success:
- git commit -a -m "$(date +'%Y-%m-%d-%H-%M-%S')"
- git push origin HEAD:master
#$GITHUB_TOKEN
```

Results in
```
$ git push origin HEAD:master
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/otruja/bitcoin-prices.git/'
```

Looking for the way to auth using token.

**Comment by otruja** [comment]
@zelima Yes, I always google.
Thanks for the link, doesn't help at all.

**Comment by zelima** [comment]
@otruja why did not? seems like you only need GitHub token

**Comment by otruja** [comment]
Best try so far:

```
language: python
python:
- "3.6"
env:
  global:
  - USER="otruja"
  - EMAIL="otruja@mail.ru"
  - REPO="bitcoin-prices"
  - GH_REPO="github.com/${USER}/${REPO}.git"
script:
- python scripts/process.py
after_success:
- git remote
- git config user.email ${EMAIL}
- git config user.name ${USER}
- git add archive/bitcoin-prices.html
- git add data/bitcoin-prices.csv
- git commit -m "$(date +'%Y-%m-%d-%H-%M-%S')"
- git push "https://${GITHUB_TOKEN}@${GH_REPO}" master > /dev/null 2>&1
```

Throws

```
Done. Your build exited with 0.
pgrep: invalid user name: otruja
```

**Comment by otruja** [comment]
Apparently $USER is a sort of system variable in *nix, so changed it in `.travis.yml` to

```
env:
  global:
  - USR="otruja"
```

Travis passes everything now. But even so, it still not push the data to the GitHub. At the least, I can see no changes or whatever in the repo.

```
$ git remote origin
$ git config user.email ${EMAIL}
$ git config user.name ${USER}
$ git add archive/bitcoin-prices.html
$ git add data/bitcoin-prices.csv
$ git commit -m "$(date +'%Y-%m-%d-%H-%M-%S')"
[detached HEAD 1fca300] 2018-05-09-15-59-03
 2 files changed, 2057 insertions(+), 2053 deletions(-)
$ git push "https://${GITHUB_TOKEN}@${GH_REPO}" master > /dev/null 2>&1
Done. Your build exited with 0.
```

**Comment by otruja** [comment]
@zelima I'm afraid there's zero mentions of `badge` in your example.
However, Google suggested [Add Travis CI build badge to README](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/issues/58), seems relevant to what you ask for. Will copy-paste this and try to make it work.

**Comment by otruja** [comment]
@zelima When you'll have a free time (I think that might take some), could you please look at [build 32](https://travis-ci.org/otruja/bitcoin-prices/builds/377789318) and [build 34](https://travis-ci.org/otruja/bitcoin-prices/builds/377789911)? They are identical, BUT somehow build 32 logged
```
$ git checkout master
Switched to branch 'master'
M	archive/bitcoin-prices.html
M	data/bitcoin-prices.csv
Your branch is up to date with 'origin/master'.
```
While build 34 somehow was unable to do the same:
```
$ git checkout master
error: Your local changes to the following files would be overwritten by checkout:
	archive/bitcoin-prices.html
Please commit your changes or stash them before you switch branches.
Aborting
```

My guess is that build 34 somehow ran on the same envrionment or something, so it either had changed files from last session (and that's why it stated that they'll be lost), or that it pulled wrong/old branch, and so there was mismatch in files and stuff. But that's just some abstract speculation on the point, I'm not sure.
